### PR TITLE
Deglobalised memstack by converting "first" and "last" variables into a memstack struct

### PR DESCRIPTION
**Pull request by hrszpuk**
## The problem this PR aims to solve
Using global variables means only a single `memstack_chain_ptr*` chain can exist across the program. This isn't very convenient for the user who may want multiple `memstack_chain_ptr*` chains to exist. For example, when in a large code base, the user may want to make a series of allocations within a function and then free all those allocation at once at the end. However, in the current code base, the coder would have to free any existing `memstack_chain_ptr*` chains because "first" and "last" are global variables and they would conflict with any new `memctack_chain_ptr*` chains created with `msinit()`.

## Solution proposed
Instead of using global variables, the library defines a new structure called `memstack`. This structure holds it's own "first" and "last" variables. This allows multiple `memstack_chain_ptr*` chains to exist by having their actions, such as adding new nodes or freeing all nodes, to be handled with the context of a `memstack*` containing the `memstack_chain_ptr*` chain's own "first" and "last". This solution solves the problem described above.

This solution modifies the functions in the library to use a `memstack*` instead of global variables. This means some functions have changed.

- `msinit()` has been replaced by `new_memstack()` not only is this function name more descriptive to what the function does but it also adds new functionality by returning a `memstack*` used for allocations and freeing the `memstack_chain_ptr*` chain.
- `msalloc()` now requires a `memstack*` argument making it's call `msalloc(memstack*)`. The `memstack*` is required to tie allocations to the local `memstack*` created using `new_memstack()`.
- `msfree()` now requires a `memstack*` arugment making it's call `msfree(memstack*)`. This is required as it must now access the `memstack_chain_ptr*` chain from a `memstack*` as well as free the `memstack*` itself.

These changes mean previous code written using the `memstack` library will no longer function if you choose to merge this pull request.

### CODE REVIEW

**Comment by Khhs167** [comment]
Hi! Thanks for the PR! The current approach used here is great and I love that you spent time commenting, the only issue is, I finished implementing this around 10 minutes before seeing this, and the style varies slightly. Currently wondering if my or your approach to the solution is the best…

The approach is similar in both of them, but the difference is function naming, and how it is built.
Your version renames the functions and enforces usage of a self-made stack, whilst mine keeps the variable names and accepts NULL.

I could happily merge this PR, but as I said, there are some minor things I am not a fan of. Leaving open for e.v discussion.

**Comment by hrszpuk** [comment]
I cannot make an educated judgement on which code is best without being about to see the code you have written. I am interested in how your implementation manages the use of multiple memstack structures, perhaps you could commit to a new branch so we can both understand each other's solutions?

**Comment by mr-cheffy** [comment]
@hrszpuk I was wondering why are you freeing the first element in the memstack at function `msfree`? and also, shouldn't the `free_node` function be replaced with `ms_free_node`?

**Comment by hrszpuk** [comment]
> @hrszpuk I was wondering why are you freeing the first element in the memstack at function `msfree`? and also, shouldn't the `free_node` function be replaced with `ms_free_node`?

Within `msfree` I pass `->first` (a pointer to the first element within the `memstack_chain_ptr*` chain) into the function `free_node`. The function `free_node` will recursively go through every `memstack_chain_ptr*` stored in the linked list and free the memory the user requested to be allocated through `msalloc`.

`free_node` isn't exposed to the user which is why I decided not to prefix it with anything. It's simply used by `msfree` and that's it.

**Comment by Khhs167** [comment]
> I cannot make an educated judgement on which code is best without being about to see the code you have written. I am interested in how your implementation manages the use of multiple memstack structures, perhaps you could commit to a new branch so we can both understand each other's solutions?

I pushed my code to https://github.com/Khhs167/memstack/tree/dev-multi
The .gitignore is updated as i am working on testing rn and i dont want to push it just yet.

**Comment by hrszpuk** [comment]
> I pushed my code to https://github.com/Khhs167/memstack/tree/dev-multi The .gitignore is updated as i am working on testing rn and i dont want to push it just yet.

Thanks, I'll check it out asap.

**Review by Khhs167 — COMMENTED** [review]
This is looking good!
Merge and aprooval/denial pending however, due to some discussion.
The code style also doesnt quite fit with the naming conventions.

**Comment by hrszpuk** [comment]
What are the issues regarding code style and naming conventions?

**Comment by Khhs167** [comment]
my main issue lies in `new_memstack()`. The others are just `msalloc` or `msfree`, so calling it `msnew()` would be more fitting.
I'll add it to the review

**Review by Khhs167 — CHANGES_REQUESTED** [review]
Alr, if you were to call new_memstack msnew or mscreate that'd be great and i'd prob merge!

**Review by Khhs167 — APPROVED** [review]
Alr we are looking great now!
I'll aproove and merge, might do the NULL options change myself later

**Pull request merged**
