### PR TITLE
New functionality, bug fixes, and enhancements

### PR DESCRIPTION
**Pull request by hrszpuk**
### Doubly linked list > Singly linked list
A singly linked list is a linked list where nodes are connected by pointer to the next node. This is a very simple, low overhead data structure, but it has it's disadvantages. In order to delete a node from the linked list, we must loop the entire list to find the previous node so the previous node can be linked to the node after the node we want to delete (e.g. Keeping the list linked together).
```
┌──────┐    ┌──────┐    ┌──────┐
│      │    │      │    │      │
│ Node ├────► Node ├────► Node │ 
│      │    │      │    │      │
└──────┘    └──────┘    └──────┘
```
A doubly linked list is a linked list where nodes are connected by pointers both to the next node and the previous node. The advantage of this over a singly linked list is that to delete a node, we already have both the previous, and next node. This means delete nodes from a doubly linked list is significantly faster than a singly linked list.
```
┌──────┐    ┌──────┐    ┌──────┐
│      ├────►      ├────►      │
│ Node │    │ Node │    │ Node │
│      ◄────┤      ◄────┤      │
└──────┘    └──────┘    └──────┘
```
Currently, the library can allocate onto the memstack, and then free the entire memstack at once. This is an incredibly useful functionality, but I believe the library would benefit from having the ability to do the following:

1. De-allocate the memstack *without* deleting the memstack itself like `msfree` does.
2. De-allocate a set number of nodes *with* and *without* deleting the user allocated memory.
3. Add new nodes to a memstack without having to allocate through the memstack library
4. Remove a node from the memstack and return the user allocated memory

Each section below details a function that can complete each functionality list above.

### msclear(memstack*)
`msclear` is used to clear a memstack without deleting the memstack itself. This is useful if further allocations are going to be made, but previous allocations must be freed. In this case, using `msfree` would require another `memstack*` to be create which is inefficient and annoying.

```c
memstack* ms = msnew();  // Create a new memstack
int* a = msalloc(ms, sizeof(int));  // Allocate onto the memstack
int* b = msalloc(ms, sizeof(int));
int* c = msalloc(ms, sizeof(int));
// ...
// Now we want to get rid of the allocations...
// But we want to make more allocations within the same scope!

// Using msfree would require us to call msnew() again which is annoying
msclear(ms);  // Instead, we "clear" the memstack's chain, but the memstack still exists!
int* x = msalloc(ms, sizeof(int));  // We can continue allocating to the memstack

// ...
// We finally free the memstack now we are done!
msfree(ms);
```

### mspop(memstack*)
`mspop` allows the user to free the last `memstack_chain_ptr*` node of a `memstack*` and get a return value of the `memstack_chain_ptr*`'s `void* ptr`. This essentially "removes" the allocation from the memstack thereby, removing the pointer from being freed by `msfree` or `msclear` later on.

```c
memstack* ms = msnew();  // Create a new memstack
int* a = msalloc(ms, sizeof(int));  // Allocate onto the memstack
int* b = msalloc(ms, sizeof(int));
int* c = msalloc(ms, sizeof(int));
// ...
// Now we want to free "a" and "b", but not "c".
// We can do this by using `mspop`.
c = mspop(ms);

msfree(ms); // Now we can free the memstack, but keep c for further use...

// ...
// The user is now in charge of "c", they must free it themselves.
free(c);
```
It's important to note, `mspop` will always remove the last element in the `memstack_chain_ptr*` chain. So, in order to "pop" a memstack node, it must have been the last one allocated.

### mspush(memstack*, void*)
`mspush` allows allocations to be added to the memstack *without* the memory having been allocated by `msalloc`. This would allow users to manage allocations themselves, and then add those allocation to the `memstack*` if they wish.

This could also be used in scenarios when other library allocate memory for the user, and the user wants it all to be freed at once.

```c
memstack* ms = msnew();  // Create a new memstack

int* a = malloc(sizeof(int));  // Allocating memory ourselves
int* b = give_me_memory();  // Allocating memory from another library's function

// ...
// The user wants these to be freed all at once, but the memory has already 
// been allocated so they cannot use msalloc()!

mspush(ms, a);  // We can add them anyway!
mspush(ms, b);

msfree(ms);  // This will free "a" and "b" for us!
```

### msrollback(memstack*, int, bool)
`msrollback` allows for many `memstack_chain_ptr*` nodes to be freed at once, but not necessarily all nodes, or memory will be freed! The user may specify the number of nodes they wish to be deleted, and whether the user memory will be deleted along with the node or not!

This would be extremely useful for deleting many nodes from the `memstack*` without deleting the memory the `memstack_chain_ptr*` was holding for the user.
```c
memstack* ms = msnew();  // Create a new memstack

int* a = msalloc(sizeof(int));  // Allocate onto the memstack
int* b = msalloc(sizeof(int));
int* c = msalloc(sizeof(int));
int* d = msalloc(sizeof(int));

// ... 
// I no longer want the memstack to manage "d" for me
// I want to free "b" and "c", without freeing "a" yet

msrollback(ms, 1, false);  // Removing the last element, without freeing the user's pointer
msrollback(ms, 2, true);  // Removing 2 elements starting at the last, free everything

*d = 100;  // "d" can still be accessed and managed by myself
*a = 100;  // "a" is managed by the memstack still, "b" and "c" are freed

msfree(a);  // "a" is gone!
free(d);  // I've freed "d" myself
```

### msprint(memstack*)
`msprint` has nothing to do with managing memory instead, it is for contributers, and users of the library to debug their programs better. `msprint` will display the given `memstack` in the console which can help understand what's on the memstack.

It's usefulness can be shown through an example:
```c
#include "memstack.h"

int main() {
    msinit();  // initialise global
    int* a = msalloc(GLOBAL_MEMSTACK, sizeof(int));  // Create allocations
    int* b = msalloc(GLOBAL_MEMSTACK, sizeof(int));
    int* c = msalloc(GLOBAL_MEMSTACK, sizeof(int));

    // Print the contents of global
    msprint(GLOBAL_MEMSTACK);

    // Modify global by freeing the last element
    free(mspop(GLOBAL_MEMSTACK));

    // print the contents of global again
    msprint(GLOBAL_MEMSTACK);

    msfree(GLOBAL_MEMSTACK); 
    return 0;
}
```
The output from this code is:
```sh
Printing memstack: 
 [-1] (nil) <--previous-- [0] Current: 0x562cff95c6d0 --next--> [1] 0x562cff95c710
 [0] 0x562cff95c6d0 <--previous-- [1] Current: 0x562cff95c710 --next--> [2] 0x562cff95c750
 [1] 0x562cff95c710 <--previous-- [2] Current: 0x562cff95c750 --next--> [3] (nil)
 [INFO] Node count: 3
 [INFO] Nodes are linked to both the next, and previous node
Printing memstack: 
 [-1] (nil) <--previous-- [0] Current: 0x562cff95c6d0 --next--> [1] 0x562cff95c710
 [0] 0x562cff95c6d0 <--previous-- [1] Current: 0x562cff95c710 --next--> [2] (nil)
 [INFO] Node count: 2
 [INFO] Nodes are linked to both the next, and previous node
```

### Fixed dead memstack node allocated every msnew() call
`msnew()` creates a "first" node but that node is never used because `msalloc` always adds a new `memstack_chain_ptr*` node to the `memstack*`. This issue was found during the implementation of `mspop` and fixed with help from `msprint`. 

## Enhancements
- Fixed "Legcacy" typo in README
- Added more code comments (idk how.. There are already so many lmao)
- Added a length property to the memstack struct

### CODE REVIEW

**Comment by hrszpuk** [comment]
I forgot to add in the linked list section, but I changed `memstack_chain_ptr*` nodes to point to both the `next` *and* the `previous` nodes. This helps with deleting nodes. That's why I was explaining the benefits of doubly linked lists, and singly linked lists, because that's one of the changes I made to the codebase.

**Review by Khhs167 — CHANGES_REQUESTED** [review]
I like how this is going! But, one thing is troubling me: booleans.
Please do not use stdbool.h, i and most people prob agree that a FALSE and a TRUE macro would be more fitting, or just passing in 0 or 1 to the functions using booleans.

**Comment by Khhs167** [comment]
Holy cow this aint my library anymore you've made 99% of it by now!

**Comment by hrszpuk** [comment]
Latest commits remove stdbool from include/memstack.h and use type int for parameter `destructive` of function `msrollback`. Users will use `1` or a macro of `1` like commonly defined `TRUE` to enable the freeing of `memstack_chain_ptr->ptr`.

**Review by Khhs167 — CHANGES_REQUESTED** [review]
This does call for a TRUE macro, then i'll merge

**Comment by hrszpuk** [comment]
I feel like adding a TRUE macro to the library could interfere with user code. If the user also defines a TRUE macro (which isn't uncommon) it will collide with the library's TRUE macro. This could also cause collision if another library the user includes also has a TRUE macro. I think it would be best to keep the parameter as it is now.

**Comment by Khhs167** [comment]
well, in case it would interfere with a TRUE macro, the user should be reccomended to define macros post-library, plus that the TRUE macro will almost always be 1 or(in certain cases) a boolean(https://stackoverflow.com/questions/17010041/why-define-true-1-1-in-a-c-boolean-macro-instead-of-simply-as-1). But it is your PR not mine, i'll just make an issue for it for later.

**Comment by Khhs167** [comment]
#7

**Review by Khhs167 — APPROVED** [review]
Alr, no true macro for now. Issue opened(#7)

**Pull request merged**
