### PR TITLE
Added make things to the examples README, it was long overdue.

### PR DESCRIPTION
**Pull request by Khhs167**
Shouldn't have to open a PR for my own repo, but I will simply because of Tokorv/Remy/Hrszpuk.

Anyhow, feel like this is just an obvious thing to add lol

### CODE REVIEW

**Comment by Khhs167** [comment]
In case @hrszpuk accepts the collaborator invitation, I'd like to request a review from him first, he poured a lot of effort into this project.

**Review by hrszpuk — APPROVED** [review]
LGTM!

**Comment by hrszpuk** [comment]
Unrelated but, when I run `make runall` I get a segfault on the mspop test.
image
This doesn't occur using `make mspop.run`.

**Comment by hrszpuk** [comment]
> Unrelated but, when I run `make runall` I get a segfault on the mspop test. image This doesn't occur using `make mspop.run`.

Any idea what could be causing this?

**Pull request merged**
