### PR TITLE
README improvements and /examples

### PR DESCRIPTION
**Pull request by hrszpuk**
## README improvements
I've made multiple small adjustments to the README, as well as, larger overhauls to a few sections. I've split the `Installation` section into `AUR installation` and `Build from source`. This should improve the readability of each section, and make reading installation information easier as it is clearer which parts are AUR and which are build from source. This also makes finding the correct installation information easier.
I've complete redone the `Usage` and `Compiling with` sections. Both sections have been combined under a single `Usage` header which also adds documentation for each function in the library, and an explanation for the global memstack.

## The new /examples directory
This contains simple, but complete in comparison with the README's, examples for using each function in memstack. Each code example is named after the function it is showing off, and every example is commented to show the reader how the function works.
I'd like to add further real world examples to the repository when memstack is used in a real world project.

## Smaller enhancements
- Changed README description
- Added a "Contributors" section using https://contrib.rocks/

### CODE REVIEW

**Comment by hrszpuk** [comment]
Forgot to mention this PR also adds the TRUE/FALSE macros mentioned in #6 and #7.

**Review by Khhs167 — CHANGES_REQUESTED** [review]
Wow! That was a lot of stuff! I'd love to merge right away, but i see one problem. `examples/build.sh`. Please do not use a shell script, but instead a GNUMakefile(Makefile). Example and style is available in the root Makefile.

**Comment by Khhs167** [comment]
> Forgot to mention this PR also adds the TRUE/FALSE macros mentioned in #6 and #7.

Then i'll be able to close upon merging

**Comment by hrszpuk** [comment]
I originally used a Makefile but it's problematic as getting command line arguments in Make is much more complicated than in Bash. I think it would be simpler (and easier) to just use Bash.

**Review by Khhs167 — APPROVED** [review]
Approve, i'll make my own Makefile alongside the bash script. Then we'll see about the future! Exciting!

**Pull request merged**
